on:
  workflow_dispatch:

jobs:
  caller:
    strategy:
      matrix:
        # 2 batches * 256 jobs each = 512 total jobs
        batch: [1, 2]
    uses: ./.github/workflows/child.yml
    with:
      batch: ${{ matrix.batch }}